[package]
name = "rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitcoin = "0.26.0"
bitcoincore-rpc = "0.15.0"
serde = "1.0"
serde_json = "1.0"
env_logger = "0.9"
log = "0.4"
